config/routes.rb
Rails.application.routes.draw do
  
  root 'login#index'
  resources :users
  
  post '/login', to: 'login#check_login'
  get 'create_json/:id', to: 'users#create_json'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_create :crypt_password
  
  CONTANTS_VARIABLE = 'a'.freeze
  
  def crypt_password(decrypt_pass)
    self.password = Digest::SHA1.hexdigest('#{decrypt_pass}')
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    puts 'ddd'
  end
  
  def check_login
    user = User.find_by(user_name: params[:user_name], password: params[:password])
    if user
      redirect_to users_path, notice: 'Login successfully.'
    else
      # @notice = 'Login error.'
      flash[:error] = 'Login error !'
      render :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create_json
    @user = User.find(params[:id])
    render json: @user
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsLogin
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/login/error.html.haml
%h1 Show errors
%p
  =@notice

app/views/login/index.html.haml
%h1 Login Rails
= form_for(:user, url: login_path) do |form|
  - if flash[:error]
    %p
      = flash[:error]
  -#- if !@notice.nil?
  -#  #error_explanation
  -#    %p
        = @notice
    -#%ul
    -#  - user.errors.full_messages.each do |message|
    -#    %li= message

  .field
    = form.label :user_name
    = form.text_field :user_name, name: :user_name
  .field
    = form.label :password
    = form.text_field :password, name: :password
  .actions
    = form.submit 'Login'

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message

  - if flash[:success]
    %p
      = flash[:success]
  .field
    = form.label :user_name
    = form.text_field :user_name, id: :user_user_name
  .field
    = form.label :password
    = form.text_field :password, id: :user_password
  .actions
    = form.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%p#notice= notice
%h1 Users
%table
  %thead
    %tr
      %th User name
      %th Password
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.user_name
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
        -#%td= link_to 'Create Json', action: :create_json, :id => user.id
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong User name:
  = @user.user_name
%p
  %strong Password:
  = @user.password
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'Back', users_path